// WARNING: This file was generated automatically (see generate_lang_java.py)

/*
 * Copyright (C) 2022 The Java Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package localization;

import java.text.MessageFormat;

/**
 * The {@L10n} is class to get localized text resources.
 *
 * @author olegshchepilov
 *
 */

public class L10n {
    public static String locale = "en";

    public enum Id {
        TITLE,
        PLAY,
        CREATE,
        CONTINUE,
        SELECT_PREDEFINED,
        LOAD_FROM_FILE,
        EXIT,
        WIDTH,
        HEIGHT,
        SAVE,
        GO_BACK,
        DIALOG_OVERWRITE_CONFIRM_TITLE,
        DIALOG_OVERWRITE_CONFIRM_TEXT,
        DIALOG_GAME_VALIDATION_TEXT,
        ERROR_THERE_IS_NO_MOLE,
        ERROR_TARGET_POINTS_MORE_THAN_BOXES,
        WISE_MOLE_LEVEL_FILE_DESCRIPTION,
        VICTORY,
        STATUSBAR_GAME_LABEL,
        STATUSBAR_STEP_COUNT_LABEL,
        STATUSBAR_STEP_COUNT_WITH_LOAD_LABEL,
        STATUSBAR_MAZE_LABEL,
        STATUSBAR_EXIT_LABEL
    }

    public static String get(Id stringId) {
        switch (stringId) {
            case TITLE:
                switch (locale) {
                    case "en":
                        return "Wise Mole";
                    case "ru":
                        return "Мудрый крот";
                    case "insl":
                        return "Mudry krot";
                    default:
                        return "{Missing(" + locale + "):TITLE}";
                }
            case PLAY:
                switch (locale) {
                    case "en":
                        return "Play";
                    case "ru":
                        return "Играть";
                    case "insl":
                        return "Igrati ";
                    default:
                        return "{Missing(" + locale + "):PLAY}";
                }
            case CREATE:
                switch (locale) {
                    case "en":
                        return "Create";
                    case "ru":
                        return "Создать";
                    case "insl":
                        return "Sozdati";
                    default:
                        return "{Missing(" + locale + "):CREATE}";
                }
            case CONTINUE:
                switch (locale) {
                    case "en":
                        return "Continue";
                    case "ru":
                        return "Продолжить";
                    case "insl":
                        return "Prodolziti";
                    default:
                        return "{Missing(" + locale + "):CONTINUE}";
                }
            case SELECT_PREDEFINED:
                switch (locale) {
                    case "en":
                        return "Select";
                    case "ru":
                        return "Выбрать ";
                    case "insl":
                        return "Izbrati";
                    default:
                        return "{Missing(" + locale + "):SELECT_PREDEFINED}";
                }
            case LOAD_FROM_FILE:
                switch (locale) {
                    case "en":
                        return "Load";
                    case "ru":
                        return "Открыть файл";
                    case "insl":
                        return "Odkryti fail";
                    default:
                        return "{Missing(" + locale + "):LOAD_FROM_FILE}";
                }
            case EXIT:
                switch (locale) {
                    case "en":
                        return "Exit";
                    case "ru":
                        return "Выйти";
                    case "insl":
                        return "Vyjdti";
                    default:
                        return "{Missing(" + locale + "):EXIT}";
                }
            case WIDTH:
                switch (locale) {
                    case "en":
                        return "Width";
                    case "ru":
                        return "Ширина";
                    case "insl":
                        return "Sirina";
                    default:
                        return "{Missing(" + locale + "):WIDTH}";
                }
            case HEIGHT:
                switch (locale) {
                    case "en":
                        return "Height";
                    case "ru":
                        return "Высота";
                    case "insl":
                        return "Vysota";
                    default:
                        return "{Missing(" + locale + "):HEIGHT}";
                }
            case SAVE:
                switch (locale) {
                    case "en":
                        return "Save";
                    case "ru":
                        return "Сохранить";
                    case "insl":
                        return "Zapisyvati";
                    default:
                        return "{Missing(" + locale + "):SAVE}";
                }
            case GO_BACK:
                switch (locale) {
                    case "en":
                        return "Go back";
                    case "ru":
                        return "Вернуться";
                    case "insl":
                        return "Vratiti se";
                    default:
                        return "{Missing(" + locale + "):GO_BACK}";
                }
            case DIALOG_OVERWRITE_CONFIRM_TITLE:
                switch (locale) {
                    case "en":
                        return "Confirm Save";
                    case "ru":
                        return "Подтверждение сохранения";
                    case "insl":
                        return "Potvrdzenje shranjenja";
                    default:
                        return "{Missing(" + locale + "):DIALOG_OVERWRITE_CONFIRM_TITLE}";
                }
            case DIALOG_OVERWRITE_CONFIRM_TEXT:
                switch (locale) {
                    case "en":
                        return "File already exists. Do you want to replace it?";
                    case "ru":
                        return "Файл уже существует. Хотите его заменить?";
                    case "insl":
                        return "Fajl uze jestvuje. Hotejete jego zameniti?";
                    default:
                        return "{Missing(" + locale + "):DIALOG_OVERWRITE_CONFIRM_TEXT}";
                }
            case DIALOG_GAME_VALIDATION_TEXT:
                switch (locale) {
                    case "en":
                        return "There is an issue: {0}. Do you want to save the level?";
                    case "ru":
                        return "Есть ошибка: {0}. Хотите сохранить уровень?";
                    case "insl":
                        return "Jest pogreska: {0}. Hotejete shraniti uravenj?";
                    default:
                        return "{Missing(" + locale + "):DIALOG_GAME_VALIDATION_TEXT}";
                }
            case ERROR_THERE_IS_NO_MOLE:
                switch (locale) {
                    case "en":
                        return "there is no mole on the field";
                    case "ru":
                        return "на поле нет крота";
                    case "insl":
                        return "krot ne jest na polju";
                    default:
                        return "{Missing(" + locale + "):ERROR_THERE_IS_NO_MOLE}";
                }
            case ERROR_TARGET_POINTS_MORE_THAN_BOXES:
                switch (locale) {
                    case "en":
                        return "target point count is more than box count";
                    case "ru":
                        return "целевых точек больше чем ящиков";
                    case "insl":
                        return "kolikost celjevyh tocek jest bolje cem skrinej";
                    default:
                        return "{Missing(" + locale + "):ERROR_TARGET_POINTS_MORE_THAN_BOXES}";
                }
            case WISE_MOLE_LEVEL_FILE_DESCRIPTION:
                switch (locale) {
                    case "en":
                        return "Wise Mole level file";
                    case "ru":
                        return "Файл уровня \"Мудрый крот\"";
                    case "insl":
                        return "Fail uravenja \"Mudry krot\"";
                    default:
                        return "{Missing(" + locale + "):WISE_MOLE_LEVEL_FILE_DESCRIPTION}";
                }
            case VICTORY:
                switch (locale) {
                    case "en":
                        return "Victory!";
                    case "ru":
                        return "Победа!";
                    case "insl":
                        return "Pobeda!";
                    default:
                        return "{Missing(" + locale + "):VICTORY}";
                }
            case STATUSBAR_GAME_LABEL:
                switch (locale) {
                    case "en":
                        return "GAME";
                    case "ru":
                        return "ИГРА";
                    case "insl":
                        return "IGRA";
                    default:
                        return "{Missing(" + locale + "):STATUSBAR_GAME_LABEL}";
                }
            case STATUSBAR_STEP_COUNT_LABEL:
                switch (locale) {
                    case "en":
                        return "Steps: ";
                    case "ru":
                        return "Шаги: ";
                    case "insl":
                        return "Kroky: ";
                    default:
                        return "{Missing(" + locale + "):STATUSBAR_STEP_COUNT_LABEL}";
                }
            case STATUSBAR_STEP_COUNT_WITH_LOAD_LABEL:
                switch (locale) {
                    case "en":
                        return "Steps with a load: ";
                    case "ru":
                        return "Шаги с грузом: ";
                    case "insl":
                        return "Kroky s bremenem: ";
                    default:
                        return "{Missing(" + locale + "):STATUSBAR_STEP_COUNT_WITH_LOAD_LABEL}";
                }
            case STATUSBAR_MAZE_LABEL:
                switch (locale) {
                    case "en":
                        return "Maze: ";
                    case "ru":
                        return "Уровень: ";
                    case "insl":
                        return "Uravenj: ";
                    default:
                        return "{Missing(" + locale + "):STATUSBAR_MAZE_LABEL}";
                }
            case STATUSBAR_EXIT_LABEL:
                switch (locale) {
                    case "en":
                        return "Exit: ";
                    case "ru":
                        return "Выход: ";
                    case "insl":
                        return "Izhod: ";
                    default:
                        return "{Missing(" + locale + "):STATUSBAR_EXIT_LABEL}";
                }
            default:
                return "{Unknown}";
        }
    }

    public static String get(Id stringId, Object... arguments) {
        return (new MessageFormat(get(stringId))).format(arguments);
    }
}
