# Every line that starts with symbol '#' is comment.
# Symbol '>' goes before an identifier.
# All the following lines (until empty line) defines translations for this identifier.
# Every translation starts with language identifier.

> PLAY
en Play
ru Играть
insl Igrati 

> CREATE
en Create
ru Создать
insl Sozdati

> CONTINUE
en Continue
ru Продолжить
insl Prodolziti

> SELECT_PREDEFINED
en Select
ru Выбрать 
insl Izbrati

> LOAD_FROM_FILE
en Load
ru Загрузить
insl Dodati

> EXIT
en Exit
ru Выйти
insl Vyjdti

> WIDTH
en Width
ru Ширина
insl Sirina

> HEIGHT
en Height
ru Высота
insl Vysota

> SAVE
en Save
ru Сохранить
insl Zapisyvati

> GO_BACK
en Go back
ru Вернуться
insl Vratiti se

> DIALOG_OVERWRITE_CONFIRM_TITLE
en Confirm Save
ru Подтверждение сохранения
insl Potvrdženje shranjenja

> DIALOG_OVERWRITE_CONFIRM_TEXT
en File already exists. Do you want to replace it?
ru Файл уже существует. Хотите его заменить?

> DIALOG_GAME_VALIDATION_TEXT
en There is an issue: {0}. Do you want to save the level?
ru Есть ошибка: {0}. Хотите сохранить уровень?

> ERROR_THERE_IS_NO_MOLE
en there is no mole on the field
ru на поле нет крота

> ERROR_TARGET_POINTS_MORE_THAN_BOXES
en target point count is more than box count
ru целевых точек больше чем ящиков

> WISE_MOLE_LEVEL_FILE_DESCRIPTION
en Wise Mole level file
ru Файл уровня "Мудрый крот"

> VICTORY
en Victory!
ru Победа!

> STATUSBAR_GAME_LABEL
en GAME
ru ИГРА

> STATUSBAR_STEP_COUNT_LABEL
en Steps: 
ru Шаги: 

> STATUSBAR_STEP_COUNT_WITH_LOAD_LABEL
en Steps with a load: 
ru Шаги с грузом: 

> STATUSBAR_MAZE_LABEL
en Maze: 
ru Уровень: 

> STATUSBAR_EXIT_LABEL
en Exit: 
ru Выход: 
